# Generated by Django 5.0.6 on 2024-07-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medistalapp', '0002_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medhistory',
            field=models.CharField(max_length=600),
        ),
    ]
